pages/test/oya.tsx

fixed build

---

.husky/pre-commit
package-lock.json
package.json

added husky

---

components/Explore/Explorenav.tsx
components/Home/homenav.tsx

Feat: Updated Navbar

---

layout/Authlayout.tsx
pages/event-dashboard/index.tsx

Page: eventdashboard

---

pages/profile/index.tsx

fix: User Profile

---

components/Home/homefooter.tsx
helpers/withAuth.tsx
pages/create-events/CreateEvents.tsx
pages/profile/index.tsx
pages/settings/data-security.tsx
pages/settings/index.tsx
pages/settings/notifications.tsx
pages/settings/preferences.tsx

Fix: added Auth

---

@types/index.d.ts
components/samplemodal.tsx
components/ui/Breadcrumbs.tsx
components/ui/Modal.tsx
components/ui/NewButton.tsx
components/ui/NewInput.tsx
components/ui/SelectInput.tsx
components/ui/Toast.tsx
helpers/withAuth.tsx
hooks/useDisclosure.tsx
package-lock.json
package.json
pages/style-guide.tsx
tailwind.config.ts

Feat: added new components

---

components/event-management/EventManagementHeader.tsx
layout/EventManagementLayout.tsx
pages/event-management/attendees/index.tsx
pages/event-management/event-overview/index.tsx
pages/event-management/index.tsx
pages/event-management/share-invites/index.tsx

Event Management Layout Set up

---

components/UserProfile/Events.tsx
components/UserProfile/FilterModal.tsx
components/UserProfile/ProfieEvent.tsx
components/UserProfile/styles.module.css

added the filter modal and worked a bit on the functionality

---

components/components/modal/auth/AuthModal.tsx
components/components/modal/auth/SignInForm.tsx
components/components/modal/auth/SignUpForm.tsx

Update the Login and signup UI

---

components/event-management/EventManagementHeader.tsx
layout/EventManagementLayout.tsx
pages/event-management/event-overview/index.tsx
pages/event-management/index.tsx

Responsiveness

---

components/Home/homefooter.tsx
components/Settings/Plans-Billings.tsx/Plans.tsx

fix: footer

---

components/Home/homenav.tsx
components/components/modal/auth/SignUP.tsx
components/components/modal/auth/SignUpForm.tsx
components/ui/Modal.tsx
http/AuthInstance.ts
http/authapi.ts
http/axios.ts
layout/Homelayout.tsx
pages/landpage-v2/index.tsx
pages/landpage-v3/index.tsx

Feat :auth

---

components/UserProfile/EditProfileModal.tsx
components/UserProfile/Events.tsx
components/UserProfile/GridEventCard.tsx
components/UserProfile/Input.tsx
components/UserProfile/ListEventCard.tsx
components/UserProfile/NoEvent.tsx
components/UserProfile/ProfieEvent.tsx
pages/profile/edit/index.tsx
pages/profile/index.tsx

added the edit page and made all pages resonsive

---

components/components/modal/auth/SignIn.tsx
components/components/modal/auth/SignUP.tsx
components/components/modal/auth/SigninWithEmail.tsx
http/AuthInstance.ts
http/authapi.ts

fixed auth

---

components/ui/PasswordPopover.tsx

fixes color for popover

---

components/components/authenticatedheader.tsx
components/components/modal/auth/SignupWithEmail.tsx
hooks/logout.tsx
http/authapi.ts
pages/index.tsx
pages/landpage-v3/index.tsx

Feat: logaout

---

components/Home/homenav.tsx
pages/verify-email/index.tsx

Created the verify email

---

components/components/authenticatedheader.tsx
components/components/modal/auth/SignIn.tsx
components/components/modal/auth/SigninWithEmail.tsx

fixes and updates

---

components/EventCreation/Page1.tsx
components/EventCreation/Page2.tsx
components/EventCreation/Page3.tsx
pages/create-events/index.tsx

> - Github Issue Example: My PR Closes #{18}
> - Linear Ticket Example: Fixes ID-#{18}

Update: overall functionality and resonsiveness fixed

---

@types/index.d.ts
components/components/authenticatedheader.tsx
components/ui/notification.tsx
package-lock.json
package.json
pages/_app.tsx
pages/index.tsx
styles/nprogress.css

feat: added notification, Fixes added pahe routes

---

components/components/authenticatedheader.tsx
helpers/withAuth.tsx
http/authapi.ts

feat: google form

---

email-temp/README.md
email-temp/example.html
email-temp/example.mjml
scripts/mjmltoHtml.ts

Feat updated google auth

---

components/components/authenticatedheader.tsx
helpers/withAuth.tsx

fixes google auth

---

components/components/authenticatedheader.tsx
http/settingsapi.ts
pages/explore/index.tsx
pages/loggedinexplore/all-categories.tsx
pages/loggedinexplore/category/[category].tsx
pages/loggedinexplore/cities.tsx
pages/loggedinexplore/city/[city].tsx
pages/loggedinexplore/depricated.tsx
pages/loggedinexplore/index.tsx

updated the navbar and fixed all pending issues

---

pages/event-dashboard/index.tsx

more fixes
